// Copyright 2023 The Tint Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

////////////////////////////////////////////////////////////////////////////////
// File generated by 'tools/src/cmd/gen' using the template:
//   src/tint/lang/spirv/builtin_fn.cc.tmpl
//
// To regenerate run: './tools/run gen'
//
//                       Do not modify this file directly
////////////////////////////////////////////////////////////////////////////////

#include "src/tint/lang/spirv/builtin_fn.h"

namespace tint::spirv {

const char* str(BuiltinFn i) {
    switch (i) {
        case BuiltinFn::kNone:
            return "<none>";
        case BuiltinFn::kArrayLength:
            return "spirv.array_length";
        case BuiltinFn::kAtomicAnd:
            return "spirv.atomic_and";
        case BuiltinFn::kAtomicCompareExchange:
            return "spirv.atomic_compare_exchange";
        case BuiltinFn::kAtomicExchange:
            return "spirv.atomic_exchange";
        case BuiltinFn::kAtomicIadd:
            return "spirv.atomic_iadd";
        case BuiltinFn::kAtomicIsub:
            return "spirv.atomic_isub";
        case BuiltinFn::kAtomicLoad:
            return "spirv.atomic_load";
        case BuiltinFn::kAtomicOr:
            return "spirv.atomic_or";
        case BuiltinFn::kAtomicSmax:
            return "spirv.atomic_smax";
        case BuiltinFn::kAtomicSmin:
            return "spirv.atomic_smin";
        case BuiltinFn::kAtomicStore:
            return "spirv.atomic_store";
        case BuiltinFn::kAtomicUmax:
            return "spirv.atomic_umax";
        case BuiltinFn::kAtomicUmin:
            return "spirv.atomic_umin";
        case BuiltinFn::kAtomicXor:
            return "spirv.atomic_xor";
        case BuiltinFn::kDot:
            return "spirv.dot";
        case BuiltinFn::kImageDrefGather:
            return "spirv.image_dref_gather";
        case BuiltinFn::kImageFetch:
            return "spirv.image_fetch";
        case BuiltinFn::kImageGather:
            return "spirv.image_gather";
        case BuiltinFn::kImageQuerySize:
            return "spirv.image_query_size";
        case BuiltinFn::kImageQuerySizeLod:
            return "spirv.image_query_size_lod";
        case BuiltinFn::kImageRead:
            return "spirv.image_read";
        case BuiltinFn::kImageSampleImplicitLod:
            return "spirv.image_sample_implicit_lod";
        case BuiltinFn::kImageSampleExplicitLod:
            return "spirv.image_sample_explicit_lod";
        case BuiltinFn::kImageSampleDrefImplicitLod:
            return "spirv.image_sample_dref_implicit_lod";
        case BuiltinFn::kImageSampleDrefExplicitLod:
            return "spirv.image_sample_dref_explicit_lod";
        case BuiltinFn::kImageWrite:
            return "spirv.image_write";
        case BuiltinFn::kMatrixTimesMatrix:
            return "spirv.matrix_times_matrix";
        case BuiltinFn::kMatrixTimesScalar:
            return "spirv.matrix_times_scalar";
        case BuiltinFn::kMatrixTimesVector:
            return "spirv.matrix_times_vector";
        case BuiltinFn::kSampledImage:
            return "spirv.sampled_image";
        case BuiltinFn::kSelect:
            return "spirv.select";
        case BuiltinFn::kVectorTimesMatrix:
            return "spirv.vector_times_matrix";
        case BuiltinFn::kVectorTimesScalar:
            return "spirv.vector_times_scalar";
    }
    return "<unknown>";
}

}  // namespace tint::spirv
