# Copyright 2023 The Tint Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

################################################################################
# File generated by 'tools/src/cmd/gen' using the template:
#   tools/src/cmd/gen/build/BUILD.cmake.tmpl
#
# To regenerate run: './tools/run gen'
#
#                       Do not modify this file directly
################################################################################

################################################################################
# Target:    tint_lang_wgsl_reader_parser
# Kind:      lib
################################################################################
tint_add_target(tint_lang_wgsl_reader_parser lib
  lang/wgsl/reader/parser/classify_template_args.cc
  lang/wgsl/reader/parser/classify_template_args.h
  lang/wgsl/reader/parser/detail.h
  lang/wgsl/reader/parser/lexer.cc
  lang/wgsl/reader/parser/lexer.h
  lang/wgsl/reader/parser/parser.cc
  lang/wgsl/reader/parser/parser.h
  lang/wgsl/reader/parser/token.cc
  lang/wgsl/reader/parser/token.h
)

tint_target_add_dependencies(tint_lang_wgsl_reader_parser lib
  tint_api_common
  tint_lang_core
  tint_lang_core_constant
  tint_lang_core_type
  tint_lang_wgsl
  tint_lang_wgsl_ast
  tint_lang_wgsl_program
  tint_lang_wgsl_resolver
  tint_lang_wgsl_sem
  tint_utils_containers
  tint_utils_diagnostic
  tint_utils_ice
  tint_utils_id
  tint_utils_macros
  tint_utils_math
  tint_utils_memory
  tint_utils_reflection
  tint_utils_result
  tint_utils_rtti
  tint_utils_strconv
  tint_utils_symbol
  tint_utils_text
  tint_utils_traits
)

################################################################################
# Target:    tint_lang_wgsl_reader_parser_test
# Kind:      test
################################################################################
tint_add_target(tint_lang_wgsl_reader_parser_test test
  lang/wgsl/reader/parser/additive_expression_test.cc
  lang/wgsl/reader/parser/argument_expression_list_test.cc
  lang/wgsl/reader/parser/assignment_stmt_test.cc
  lang/wgsl/reader/parser/bitwise_expression_test.cc
  lang/wgsl/reader/parser/break_stmt_test.cc
  lang/wgsl/reader/parser/bug_cases_test.cc
  lang/wgsl/reader/parser/call_stmt_test.cc
  lang/wgsl/reader/parser/classify_template_args_test.cc
  lang/wgsl/reader/parser/compound_stmt_test.cc
  lang/wgsl/reader/parser/const_literal_test.cc
  lang/wgsl/reader/parser/continue_stmt_test.cc
  lang/wgsl/reader/parser/continuing_stmt_test.cc
  lang/wgsl/reader/parser/core_lhs_expression_test.cc
  lang/wgsl/reader/parser/diagnostic_attribute_test.cc
  lang/wgsl/reader/parser/diagnostic_control_test.cc
  lang/wgsl/reader/parser/diagnostic_directive_test.cc
  lang/wgsl/reader/parser/enable_directive_test.cc
  lang/wgsl/reader/parser/error_msg_test.cc
  lang/wgsl/reader/parser/error_resync_test.cc
  lang/wgsl/reader/parser/expression_test.cc
  lang/wgsl/reader/parser/for_stmt_test.cc
  lang/wgsl/reader/parser/function_attribute_list_test.cc
  lang/wgsl/reader/parser/function_attribute_test.cc
  lang/wgsl/reader/parser/function_decl_test.cc
  lang/wgsl/reader/parser/function_header_test.cc
  lang/wgsl/reader/parser/global_constant_decl_test.cc
  lang/wgsl/reader/parser/global_decl_test.cc
  lang/wgsl/reader/parser/global_variable_decl_test.cc
  lang/wgsl/reader/parser/helper_test.cc
  lang/wgsl/reader/parser/helper_test.h
  lang/wgsl/reader/parser/if_stmt_test.cc
  lang/wgsl/reader/parser/increment_decrement_stmt_test.cc
  lang/wgsl/reader/parser/lexer_test.cc
  lang/wgsl/reader/parser/lhs_expression_test.cc
  lang/wgsl/reader/parser/loop_stmt_test.cc
  lang/wgsl/reader/parser/math_expression_test.cc
  lang/wgsl/reader/parser/multiplicative_expression_test.cc
  lang/wgsl/reader/parser/param_list_test.cc
  lang/wgsl/reader/parser/paren_expression_test.cc
  lang/wgsl/reader/parser/parser_test.cc
  lang/wgsl/reader/parser/primary_expression_test.cc
  lang/wgsl/reader/parser/relational_expression_test.cc
  lang/wgsl/reader/parser/require_directive_test.cc
  lang/wgsl/reader/parser/reserved_keyword_test.cc
  lang/wgsl/reader/parser/shift_expression_test.cc
  lang/wgsl/reader/parser/singular_expression_test.cc
  lang/wgsl/reader/parser/statement_test.cc
  lang/wgsl/reader/parser/statements_test.cc
  lang/wgsl/reader/parser/struct_attribute_decl_test.cc
  lang/wgsl/reader/parser/struct_body_decl_test.cc
  lang/wgsl/reader/parser/struct_decl_test.cc
  lang/wgsl/reader/parser/struct_member_attribute_decl_test.cc
  lang/wgsl/reader/parser/struct_member_attribute_test.cc
  lang/wgsl/reader/parser/struct_member_test.cc
  lang/wgsl/reader/parser/switch_body_test.cc
  lang/wgsl/reader/parser/switch_stmt_test.cc
  lang/wgsl/reader/parser/token_test.cc
  lang/wgsl/reader/parser/type_alias_test.cc
  lang/wgsl/reader/parser/type_decl_test.cc
  lang/wgsl/reader/parser/unary_expression_test.cc
  lang/wgsl/reader/parser/variable_attribute_list_test.cc
  lang/wgsl/reader/parser/variable_attribute_test.cc
  lang/wgsl/reader/parser/variable_decl_test.cc
  lang/wgsl/reader/parser/variable_ident_decl_test.cc
  lang/wgsl/reader/parser/variable_qualifier_test.cc
  lang/wgsl/reader/parser/variable_stmt_test.cc
  lang/wgsl/reader/parser/while_stmt_test.cc
)

tint_target_add_dependencies(tint_lang_wgsl_reader_parser_test test
  tint_api_common
  tint_lang_core
  tint_lang_core_constant
  tint_lang_core_type
  tint_lang_wgsl
  tint_lang_wgsl_ast
  tint_lang_wgsl_ast_test
  tint_lang_wgsl_program
  tint_lang_wgsl_reader_parser
  tint_lang_wgsl_resolver
  tint_lang_wgsl_sem
  tint_utils_containers
  tint_utils_diagnostic
  tint_utils_ice
  tint_utils_id
  tint_utils_macros
  tint_utils_math
  tint_utils_memory
  tint_utils_reflection
  tint_utils_result
  tint_utils_rtti
  tint_utils_symbol
  tint_utils_text
  tint_utils_traits
)

tint_target_add_external_dependencies(tint_lang_wgsl_reader_parser_test test
  "gtest"
)
