# Copyright 2023 The Tint Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

################################################################################
# File generated by tools/src/cmd/gen
# using the template:
#   tools/src/cmd/gen/build/BUILD.cmake.tmpl
#
# Do not modify this file directly
################################################################################

tint_add_target("cmd/test:test_cmd"
  cmd/test/main_test.cc
)

tint_target_add_dependencies("cmd/test:test_cmd"
  "api"
  "cmd/common:test"
  "lang/core/constant:test"
  "lang/core/intrinsic:test"
  "lang/core/type:test"
  "lang/core:test"
  "lang/wgsl/ast/transform:test"
  "lang/wgsl/ast:test"
  "lang/wgsl/helpers:test"
  "lang/wgsl/inspector:test"
  "lang/wgsl/program:test"
  "lang/wgsl/reader/parser:test"
  "lang/wgsl/resolver:test"
  "lang/wgsl/sem:test"
  "lang/wgsl/writer/ast_printer:test"
  "lang/wgsl:test"
  "utils/cli:test"
  "utils/command:test"
  "utils/containers:test"
  "utils/diagnostic:test"
  "utils/file:test"
  "utils/ice"
  "utils/ice:test"
  "utils/macros"
  "utils/macros:test"
  "utils/math:test"
  "utils/memory:test"
  "utils/reflection:test"
  "utils/result:test"
  "utils/rtti:test"
  "utils/strconv:test"
  "utils/symbol:test"
  "utils/text:test"
  "utils/traits:test"
)

if (TINT_BUILD_GLSL_WRITER)
  tint_target_add_dependencies("cmd/test:test_cmd"
    "lang/glsl/writer/ast_printer:test"
  )
endif(TINT_BUILD_GLSL_WRITER)

if (TINT_BUILD_HLSL_WRITER)
  tint_target_add_dependencies("cmd/test:test_cmd"
    "lang/hlsl/writer/ast_printer:test"
  )
endif(TINT_BUILD_HLSL_WRITER)

if (TINT_BUILD_IR)
  tint_target_add_dependencies("cmd/test:test_cmd"
    "lang/core/ir/transform:test"
    "lang/core/ir:test"
    "lang/wgsl/reader/program_to_ir:test"
    "lang/wgsl/writer/ir_to_program:test"
  )
endif(TINT_BUILD_IR)

if (TINT_BUILD_MSL_WRITER)
  tint_target_add_dependencies("cmd/test:test_cmd"
    "lang/msl/writer/ast_printer:test"
    "lang/msl/writer/common:test"
  )
endif(TINT_BUILD_MSL_WRITER)

if (TINT_BUILD_MSL_WRITER  AND  TINT_BUILD_IR)
  tint_target_add_dependencies("cmd/test:test_cmd"
    "lang/msl/writer/printer:test"
  )
endif(TINT_BUILD_MSL_WRITER  AND  TINT_BUILD_IR)

if (TINT_BUILD_SPV_READER)
  tint_target_add_dependencies("cmd/test:test_cmd"
    "lang/spirv/reader/ast_parser:test"
  )
endif(TINT_BUILD_SPV_READER)

if (TINT_BUILD_SPV_WRITER)
  tint_target_add_dependencies("cmd/test:test_cmd"
    "lang/spirv/writer/ast_printer:test"
    "lang/spirv/writer/common:test"
    "lang/spirv/writer:test"
  )
endif(TINT_BUILD_SPV_WRITER)

if (TINT_BUILD_SPV_WRITER  AND  TINT_BUILD_IR)
  tint_target_add_dependencies("cmd/test:test_cmd"
    "lang/spirv/writer/raise:test"
  )
endif(TINT_BUILD_SPV_WRITER  AND  TINT_BUILD_IR)

tint_target_set_output_name("cmd/test:test_cmd" "tint_unittests")
