// Copyright 2025 The Dawn & Tint Authors
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions are met:
//
// 1. Redistributions of source code must retain the above copyright notice, this
//    list of conditions and the following disclaimer.
//
// 2. Redistributions in binary form must reproduce the above copyright notice,
//    this list of conditions and the following disclaimer in the documentation
//    and/or other materials provided with the distribution.
//
// 3. Neither the name of the copyright holder nor the names of its
//    contributors may be used to endorse or promote products derived from
//    this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
// AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
// IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
// DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
// FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
// DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
// SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
// CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
// OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

////////////////////////////////////////////////////////////////////////////////
// File generated by 'tools/src/cmd/gen' using the template:
//   src/tint/lang/wgsl/enums_test.cc.tmpl
//
// To regenerate run: './tools/run gen'
//
//                       Do not modify this file directly
////////////////////////////////////////////////////////////////////////////////

// clang-format off

#include <string>

#include "gtest/gtest.h"

#include "src/tint/lang/wgsl/enums.h"
#include "src/tint/utils/text/string.h"

namespace tint::wgsl {
namespace {

namespace core_diagnostic_rule_tests {
namespace parse_print_tests {

struct CoreDiagnosticRuleCase {
    const char* string;
    CoreDiagnosticRule value;
};

inline std::ostream& operator<<(std::ostream& out, CoreDiagnosticRuleCase c) {
    return out << "'" << std::string(c.string) << "'";
}

static constexpr CoreDiagnosticRuleCase kValidCoreDiagnosticRuleCases[] = {
    {"derivative_uniformity", CoreDiagnosticRule::kDerivativeUniformity},
    {"subgroup_uniformity", CoreDiagnosticRule::kSubgroupUniformity},
};

static constexpr CoreDiagnosticRuleCase kInvalidCoreDiagnosticRuleCases[] = {
    {"deriative_unccformity", CoreDiagnosticRule::kUndefined},
    {"dlivative_3iformiy", CoreDiagnosticRule::kUndefined},
    {"derivative_uniforVity", CoreDiagnosticRule::kUndefined},
    {"s1bgroup_uniformity", CoreDiagnosticRule::kUndefined},
    {"subgrouqq_unifJrmty", CoreDiagnosticRule::kUndefined},
    {"sub77roup_ulliformity", CoreDiagnosticRule::kUndefined},
};

using CoreDiagnosticRuleParseTest = testing::TestWithParam<CoreDiagnosticRuleCase>;

TEST_P(CoreDiagnosticRuleParseTest, Parse) {
    const char* string = GetParam().string;
    CoreDiagnosticRule expect = GetParam().value;
    EXPECT_EQ(expect, ParseCoreDiagnosticRule(string));
}

INSTANTIATE_TEST_SUITE_P(ValidCoreDiagnosticRuleCases, CoreDiagnosticRuleParseTest, testing::ValuesIn(kValidCoreDiagnosticRuleCases));
INSTANTIATE_TEST_SUITE_P(InvalidCoreDiagnosticRuleCases, CoreDiagnosticRuleParseTest, testing::ValuesIn(kInvalidCoreDiagnosticRuleCases));

using CoreDiagnosticRulePrintTest = testing::TestWithParam<CoreDiagnosticRuleCase>;

TEST_P(CoreDiagnosticRulePrintTest, Print) {
    CoreDiagnosticRule value = GetParam().value;
    const char* expect = GetParam().string;
    EXPECT_EQ(expect, ToString(value));
}

INSTANTIATE_TEST_SUITE_P(ValidCoreDiagnosticRuleCases, CoreDiagnosticRulePrintTest, testing::ValuesIn(kValidCoreDiagnosticRuleCases));

}  // namespace parse_print_tests
}  // namespace core_diagnostic_rule_tests

namespace chromium_diagnostic_rule_tests {
namespace parse_print_tests {

struct ChromiumDiagnosticRuleCase {
    const char* string;
    ChromiumDiagnosticRule value;
};

inline std::ostream& operator<<(std::ostream& out, ChromiumDiagnosticRuleCase c) {
    return out << "'" << std::string(c.string) << "'";
}

static constexpr ChromiumDiagnosticRuleCase kValidChromiumDiagnosticRuleCases[] = {
    {"subgroup_matrix_uniformity", ChromiumDiagnosticRule::kSubgroupMatrixUniformity},
    {"unreachable_code", ChromiumDiagnosticRule::kUnreachableCode},
};

static constexpr ChromiumDiagnosticRuleCase kInvalidChromiumDiagnosticRuleCases[] = {
    {"subgroppHp_matriqq_uiformity", ChromiumDiagnosticRule::kUndefined},
    {"subroup_matrcx_niformit", ChromiumDiagnosticRule::kUndefined},
    {"subroupGmatrbx_uniformity", ChromiumDiagnosticRule::kUndefined},
    {"vnriiachable_code", ChromiumDiagnosticRule::kUndefined},
    {"unreac8ablWW_code", ChromiumDiagnosticRule::kUndefined},
    {"unreMchablxxcode", ChromiumDiagnosticRule::kUndefined},
};

using ChromiumDiagnosticRuleParseTest = testing::TestWithParam<ChromiumDiagnosticRuleCase>;

TEST_P(ChromiumDiagnosticRuleParseTest, Parse) {
    const char* string = GetParam().string;
    ChromiumDiagnosticRule expect = GetParam().value;
    EXPECT_EQ(expect, ParseChromiumDiagnosticRule(string));
}

INSTANTIATE_TEST_SUITE_P(ValidChromiumDiagnosticRuleCases, ChromiumDiagnosticRuleParseTest, testing::ValuesIn(kValidChromiumDiagnosticRuleCases));
INSTANTIATE_TEST_SUITE_P(InvalidChromiumDiagnosticRuleCases, ChromiumDiagnosticRuleParseTest, testing::ValuesIn(kInvalidChromiumDiagnosticRuleCases));

using ChromiumDiagnosticRulePrintTest = testing::TestWithParam<ChromiumDiagnosticRuleCase>;

TEST_P(ChromiumDiagnosticRulePrintTest, Print) {
    ChromiumDiagnosticRule value = GetParam().value;
    const char* expect = GetParam().string;
    EXPECT_EQ(expect, ToString(value));
}

INSTANTIATE_TEST_SUITE_P(ValidChromiumDiagnosticRuleCases, ChromiumDiagnosticRulePrintTest, testing::ValuesIn(kValidChromiumDiagnosticRuleCases));

}  // namespace parse_print_tests
}  // namespace chromium_diagnostic_rule_tests

namespace diagnostic_severity_tests {
namespace parse_print_tests {

struct DiagnosticSeverityCase {
    const char* string;
    DiagnosticSeverity value;
};

inline std::ostream& operator<<(std::ostream& out, DiagnosticSeverityCase c) {
    return out << "'" << std::string(c.string) << "'";
}

static constexpr DiagnosticSeverityCase kValidDiagnosticSeverityCases[] = {
    {"error", DiagnosticSeverity::kError},
    {"info", DiagnosticSeverity::kInfo},
    {"off", DiagnosticSeverity::kOff},
    {"warning", DiagnosticSeverity::kWarning},
};

static constexpr DiagnosticSeverityCase kInvalidDiagnosticSeverityCases[] = {
    {"eggor", DiagnosticSeverity::kUndefined},
    {"VoX", DiagnosticSeverity::kUndefined},
    {"erro3", DiagnosticSeverity::kUndefined},
    {"infE", DiagnosticSeverity::kUndefined},
    {"TTPfo", DiagnosticSeverity::kUndefined},
    {"xxnfo", DiagnosticSeverity::kUndefined},
    {"44ff", DiagnosticSeverity::kUndefined},
    {"oSVVf", DiagnosticSeverity::kUndefined},
    {"RR2", DiagnosticSeverity::kUndefined},
    {"wFni9g", DiagnosticSeverity::kUndefined},
    {"waring", DiagnosticSeverity::kUndefined},
    {"VOORRHng", DiagnosticSeverity::kUndefined},
};

using DiagnosticSeverityParseTest = testing::TestWithParam<DiagnosticSeverityCase>;

TEST_P(DiagnosticSeverityParseTest, Parse) {
    const char* string = GetParam().string;
    DiagnosticSeverity expect = GetParam().value;
    EXPECT_EQ(expect, ParseDiagnosticSeverity(string));
}

INSTANTIATE_TEST_SUITE_P(ValidDiagnosticSeverityCases, DiagnosticSeverityParseTest, testing::ValuesIn(kValidDiagnosticSeverityCases));
INSTANTIATE_TEST_SUITE_P(InvalidDiagnosticSeverityCases, DiagnosticSeverityParseTest, testing::ValuesIn(kInvalidDiagnosticSeverityCases));

using DiagnosticSeverityPrintTest = testing::TestWithParam<DiagnosticSeverityCase>;

TEST_P(DiagnosticSeverityPrintTest, Print) {
    DiagnosticSeverity value = GetParam().value;
    const char* expect = GetParam().string;
    EXPECT_EQ(expect, ToString(value));
}

INSTANTIATE_TEST_SUITE_P(ValidDiagnosticSeverityCases, DiagnosticSeverityPrintTest, testing::ValuesIn(kValidDiagnosticSeverityCases));

}  // namespace parse_print_tests
}  // namespace diagnostic_severity_tests

namespace parse_print_tests {

struct ExtensionCase {
    const char* string;
    Extension value;
};

inline std::ostream& operator<<(std::ostream& out, ExtensionCase c) {
    return out << "'" << std::string(c.string) << "'";
}

static constexpr ExtensionCase kValidExtensionCases[] = {
    {"chromium_disable_uniformity_analysis", Extension::kChromiumDisableUniformityAnalysis},
    {"chromium_experimental_barycentric_coord", Extension::kChromiumExperimentalBarycentricCoord},
    {"chromium_experimental_dynamic_binding", Extension::kChromiumExperimentalDynamicBinding},
    {"chromium_experimental_framebuffer_fetch", Extension::kChromiumExperimentalFramebufferFetch},
    {"chromium_experimental_pixel_local", Extension::kChromiumExperimentalPixelLocal},
    {"chromium_experimental_resource_table", Extension::kChromiumExperimentalResourceTable},
    {"chromium_experimental_subgroup_matrix", Extension::kChromiumExperimentalSubgroupMatrix},
    {"chromium_experimental_subgroup_size_control", Extension::kChromiumExperimentalSubgroupSizeControl},
    {"chromium_internal_graphite", Extension::kChromiumInternalGraphite},
    {"chromium_internal_input_attachments", Extension::kChromiumInternalInputAttachments},
    {"clip_distances", Extension::kClipDistances},
    {"dual_source_blending", Extension::kDualSourceBlending},
    {"f16", Extension::kF16},
    {"primitive_index", Extension::kPrimitiveIndex},
    {"subgroups", Extension::kSubgroups},
};

static constexpr ExtensionCase kInvalidExtensionCases[] = {
    {"chromium_disable_ynifority_analysis", Extension::kUndefined},
    {"c77nromium_disable_rrniformity_analysGll", Extension::kUndefined},
    {"chromium_disable_uniform00ty_4nalysis", Extension::kUndefined},
    {"chomium_experiooetal_barcentric_coord", Extension::kUndefined},
    {"chromium_experimentl_barycentzzc_coord", Extension::kUndefined},
    {"chromium_expperimental1barycentric_coori", Extension::kUndefined},
    {"chromium_experimental_dyXXamic_binding", Extension::kUndefined},
    {"chromi55m_eIIperimental_dynnami99_binding", Extension::kUndefined},
    {"chroSSium_experiaaYntal_dynamic_binrrHHng", Extension::kUndefined},
    {"chromum_xperimentalframebuffHrkkfetch", Extension::kUndefined},
    {"chrojium_xRReimental_frgmebuffer_fetch", Extension::kUndefined},
    {"hromium_experimental_ramebbffer_fetch", Extension::kUndefined},
    {"chromium_experimentjl_pixel_local", Extension::kUndefined},
    {"chroium_experimental_pixel_local", Extension::kUndefined},
    {"cromium_qxperimental_pixl_local", Extension::kUndefined},
    {"chromium_experimetal_resource_NNable", Extension::kUndefined},
    {"chrvvmium_experimentl_resource_tble", Extension::kUndefined},
    {"chromium_experiental_resource_taQQle", Extension::kUndefined},
    {"hromium_exprimertal_subgroup_ffatrix", Extension::kUndefined},
    {"chromium_ejperimental_subgroup_matrix", Extension::kUndefined},
    {"chromium_expewim8n2al_subgroupNNmatrix", Extension::kUndefined},
    {"chromium_experimental_sbgroup_size_control", Extension::kUndefined},
    {"chromium_experimental_subgroup_size_conrrrol", Extension::kUndefined},
    {"chromium_expGrimental_subgroup_size_control", Extension::kUndefined},
    {"chromium_internalFFgraphite", Extension::kUndefined},
    {"chroium_interEal_aphite", Extension::kUndefined},
    {"chromirrm_inernal_graphite", Extension::kUndefined},
    {"chromium_internal_inpu_attahments", Extension::kUndefined},
    {"chomium_internDlXinputJJattachments", Extension::kUndefined},
    {"ch8omium_interal_input_attacmets", Extension::kUndefined},
    {"clip_ksa11ce", Extension::kUndefined},
    {"cli_distances", Extension::kUndefined},
    {"Jlp_distances", Extension::kUndefined},
    {"dual_source_clending", Extension::kUndefined},
    {"dual_sOurce_blending", Extension::kUndefined},
    {"dualKKs__urce_blttvnding", Extension::kUndefined},
    {"xx8", Extension::kUndefined},
    {"__F", Extension::kUndefined},
    {"f1q", Extension::kUndefined},
    {"33r6mitive_Ondex", Extension::kUndefined},
    {"p9imitiQQtt_6oodex", Extension::kUndefined},
    {"prmit66ve_index", Extension::kUndefined},
    {"zzxbO6rops", Extension::kUndefined},
    {"subgyyoups", Extension::kUndefined},
    {"HHugroZs", Extension::kUndefined},
};

using ExtensionParseTest = testing::TestWithParam<ExtensionCase>;

TEST_P(ExtensionParseTest, Parse) {
    const char* string = GetParam().string;
    Extension expect = GetParam().value;
    EXPECT_EQ(expect, ParseExtension(string));
}

INSTANTIATE_TEST_SUITE_P(ValidExtensionCases, ExtensionParseTest, testing::ValuesIn(kValidExtensionCases));
INSTANTIATE_TEST_SUITE_P(InvalidExtensionCases, ExtensionParseTest, testing::ValuesIn(kInvalidExtensionCases));

using ExtensionPrintTest = testing::TestWithParam<ExtensionCase>;

TEST_P(ExtensionPrintTest, Print) {
    Extension value = GetParam().value;
    const char* expect = GetParam().string;
    EXPECT_EQ(expect, ToString(value));
}

INSTANTIATE_TEST_SUITE_P(ValidExtensionCases, ExtensionPrintTest, testing::ValuesIn(kValidExtensionCases));

}  // namespace parse_print_tests

namespace parse_print_tests {

struct LanguageFeatureCase {
    const char* string;
    LanguageFeature value;
};

inline std::ostream& operator<<(std::ostream& out, LanguageFeatureCase c) {
    return out << "'" << std::string(c.string) << "'";
}

static constexpr LanguageFeatureCase kValidLanguageFeatureCases[] = {
    {"buffer_view", LanguageFeature::kBufferView},
    {"chromium_print", LanguageFeature::kChromiumPrint},
    {"chromium_testing_experimental", LanguageFeature::kChromiumTestingExperimental},
    {"chromium_testing_shipped", LanguageFeature::kChromiumTestingShipped},
    {"chromium_testing_shipped_with_killswitch", LanguageFeature::kChromiumTestingShippedWithKillswitch},
    {"chromium_testing_unimplemented", LanguageFeature::kChromiumTestingUnimplemented},
    {"chromium_testing_unsafe_experimental", LanguageFeature::kChromiumTestingUnsafeExperimental},
    {"fragment_depth", LanguageFeature::kFragmentDepth},
    {"immediate_address_space", LanguageFeature::kImmediateAddressSpace},
    {"packed_4x8_integer_dot_product", LanguageFeature::kPacked4X8IntegerDotProduct},
    {"pointer_composite_access", LanguageFeature::kPointerCompositeAccess},
    {"readonly_and_readwrite_storage_textures", LanguageFeature::kReadonlyAndReadwriteStorageTextures},
    {"sized_binding_array", LanguageFeature::kSizedBindingArray},
    {"subgroup_id", LanguageFeature::kSubgroupId},
    {"subgroup_uniformity", LanguageFeature::kSubgroupUniformity},
    {"texel_buffers", LanguageFeature::kTexelBuffers},
    {"texture_and_sampler_let", LanguageFeature::kTextureAndSamplerLet},
    {"uniform_buffer_standard_layout", LanguageFeature::kUniformBufferStandardLayout},
    {"unrestricted_pointer_parameters", LanguageFeature::kUnrestrictedPointerParameters},
};

static constexpr LanguageFeatureCase kInvalidLanguageFeatureCases[] = {
    {"WWufer_viq4w", LanguageFeature::kUndefined},
    {"buffeOO_iew", LanguageFeature::kUndefined},
    {"bYohfr_vew", LanguageFeature::kUndefined},
    {"cromiu_prit", LanguageFeature::kUndefined},
    {"chomium_priFt", LanguageFeature::kUndefined},
    {"whromiu_print", LanguageFeature::kUndefined},
    {"chromium_tGsKingefferimental", LanguageFeature::kUndefined},
    {"chrqmium_testKKng_experimental", LanguageFeature::kUndefined},
    {"chromium_Fmmsting_experi3ental", LanguageFeature::kUndefined},
    {"chromium_tesing_shipped", LanguageFeature::kUndefined},
    {"chromqum_testing_shiped", LanguageFeature::kUndefined},
    {"chromium_tbbstng_shipped", LanguageFeature::kUndefined},
    {"chromium_testing_shiped_wth_killswiitch", LanguageFeature::kUndefined},
    {"chomium_testing_shqpped_with_killswitOOh", LanguageFeature::kUndefined},
    {"chromium_testing_sTTipvved_with_killswitch", LanguageFeature::kUndefined},
    {"chromium_testing_unimpFFemented", LanguageFeature::kUndefined},
    {"chrofium_testnQ_uP00mplemented", LanguageFeature::kUndefined},
    {"chromium_testiPg_unimplemented", LanguageFeature::kUndefined},
    {"chsomium_testing_unsafe77experimental", LanguageFeature::kUndefined},
    {"chromium_tebbting_unsafe_expeCimentRRl", LanguageFeature::kUndefined},
    {"chromium_testing_unsafe_experimentaXX", LanguageFeature::kUndefined},
    {"fragmqntdepCCOOO", LanguageFeature::kUndefined},
    {"frasment_eutL", LanguageFeature::kUndefined},
    {"fXagment_depth", LanguageFeature::kUndefined},
    {"immediate_address_spac", LanguageFeature::kUndefined},
    {"immeiaOe_areqqs_space", LanguageFeature::kUndefined},
    {"immed22ate_address_space", LanguageFeature::kUndefined},
    {"packe0_zzy8_inXXeger_dot_produc", LanguageFeature::kUndefined},
    {"packed_4x8_inteier_doVPproduct", LanguageFeature::kUndefined},
    {"pacCed_x8_integenn_dot_product", LanguageFeature::kUndefined},
    {"pintHH_qqomposite_aAAcess", LanguageFeature::kUndefined},
    {"ointer_composite_access", LanguageFeature::kUndefined},
    {"poiterKKcomposie_acfess", LanguageFeature::kUndefined},
    {"readonly_ggnd_readwrite_sPorage_xturel", LanguageFeature::kUndefined},
    {"readonly_and_readwrite_storage_texture", LanguageFeature::kUndefined},
    {"readcnly_and_reaNwrite_stTTrag4_textures", LanguageFeature::kUndefined},
    {"slzepp7_bining_array", LanguageFeature::kUndefined},
    {"sgzed_bndigNNzarray", LanguageFeature::kUndefined},
    {"sized_indibbg_XXrauu", LanguageFeature::kUndefined},
    {"subgrou_id", LanguageFeature::kUndefined},
    {"KbQrou88id", LanguageFeature::kUndefined},
    {"sub9ropqid", LanguageFeature::kUndefined},
    {"subgroup_uniform11ty", LanguageFeature::kUndefined},
    {"subgr22ip_unifFrmity", LanguageFeature::kUndefined},
    {"su77roup_uniformity", LanguageFeature::kUndefined},
    {"texNNl_buf2rs", LanguageFeature::kUndefined},
    {"texel_buffeVVs", LanguageFeature::kUndefined},
    {"te11elwbWWfFers", LanguageFeature::kUndefined},
    {"textue_and_samplerwwlet", LanguageFeature::kUndefined},
    {"texture_aDd_sampler_let", LanguageFeature::kUndefined},
    {"texture_aKdsampler_let", LanguageFeature::kUndefined},
    {"unifPPf11_buffer_standard_lryouh", LanguageFeature::kUndefined},
    {"uniform_buffer_stndard_layout", LanguageFeature::kUndefined},
    {"uniform_buffer_standard_layouYY", LanguageFeature::kUndefined},
    {"VnrtstricHHedkkpointer_paraeters", LanguageFeature::kUndefined},
    {"urrrestricted_pointer_parameters", LanguageFeature::kUndefined},
    {"unreWWtricted_pointess_paraeters", LanguageFeature::kUndefined},
};

using LanguageFeatureParseTest = testing::TestWithParam<LanguageFeatureCase>;

TEST_P(LanguageFeatureParseTest, Parse) {
    const char* string = GetParam().string;
    LanguageFeature expect = GetParam().value;
    EXPECT_EQ(expect, ParseLanguageFeature(string));
}

INSTANTIATE_TEST_SUITE_P(ValidLanguageFeatureCases, LanguageFeatureParseTest, testing::ValuesIn(kValidLanguageFeatureCases));
INSTANTIATE_TEST_SUITE_P(InvalidLanguageFeatureCases, LanguageFeatureParseTest, testing::ValuesIn(kInvalidLanguageFeatureCases));

using LanguageFeaturePrintTest = testing::TestWithParam<LanguageFeatureCase>;

TEST_P(LanguageFeaturePrintTest, Print) {
    LanguageFeature value = GetParam().value;
    const char* expect = GetParam().string;
    EXPECT_EQ(expect, ToString(value));
}

INSTANTIATE_TEST_SUITE_P(ValidLanguageFeatureCases, LanguageFeaturePrintTest, testing::ValuesIn(kValidLanguageFeatureCases));

}  // namespace parse_print_tests

}  // namespace
}  // namespace tint::wgsl

// clang-format on
