#version 310 es

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;
void unused_entry_point() {
  return;
}
struct S {
  vec3 v;
  uint pad;
};

layout(binding = 0, std140) uniform U_block_ubo {
  S inner;
} U;

void f() {
  vec3 v = U.inner.v;
  float x = U.inner.v.x;
  float y = U.inner.v.y;
  float z = U.inner.v.z;
  vec2 xx = U.inner.v.xx;
  vec2 xy = U.inner.v.xy;
  vec2 xz = U.inner.v.xz;
  vec2 yx = U.inner.v.yx;
  vec2 yy = U.inner.v.yy;
  vec2 yz = U.inner.v.yz;
  vec2 zx = U.inner.v.zx;
  vec2 zy = U.inner.v.zy;
  vec2 zz = U.inner.v.zz;
  vec3 xxx = U.inner.v.xxx;
  vec3 xxy = U.inner.v.xxy;
  vec3 xxz = U.inner.v.xxz;
  vec3 xyx = U.inner.v.xyx;
  vec3 xyy = U.inner.v.xyy;
  vec3 xyz = U.inner.v.xyz;
  vec3 xzx = U.inner.v.xzx;
  vec3 xzy = U.inner.v.xzy;
  vec3 xzz = U.inner.v.xzz;
  vec3 yxx = U.inner.v.yxx;
  vec3 yxy = U.inner.v.yxy;
  vec3 yxz = U.inner.v.yxz;
  vec3 yyx = U.inner.v.yyx;
  vec3 yyy = U.inner.v.yyy;
  vec3 yyz = U.inner.v.yyz;
  vec3 yzx = U.inner.v.yzx;
  vec3 yzy = U.inner.v.yzy;
  vec3 yzz = U.inner.v.yzz;
  vec3 zxx = U.inner.v.zxx;
  vec3 zxy = U.inner.v.zxy;
  vec3 zxz = U.inner.v.zxz;
  vec3 zyx = U.inner.v.zyx;
  vec3 zyy = U.inner.v.zyy;
  vec3 zyz = U.inner.v.zyz;
  vec3 zzx = U.inner.v.zzx;
  vec3 zzy = U.inner.v.zzy;
  vec3 zzz = U.inner.v.zzz;
  vec4 xxxx = U.inner.v.xxxx;
  vec4 xxxy = U.inner.v.xxxy;
  vec4 xxxz = U.inner.v.xxxz;
  vec4 xxyx = U.inner.v.xxyx;
  vec4 xxyy = U.inner.v.xxyy;
  vec4 xxyz = U.inner.v.xxyz;
  vec4 xxzx = U.inner.v.xxzx;
  vec4 xxzy = U.inner.v.xxzy;
  vec4 xxzz = U.inner.v.xxzz;
  vec4 xyxx = U.inner.v.xyxx;
  vec4 xyxy = U.inner.v.xyxy;
  vec4 xyxz = U.inner.v.xyxz;
  vec4 xyyx = U.inner.v.xyyx;
  vec4 xyyy = U.inner.v.xyyy;
  vec4 xyyz = U.inner.v.xyyz;
  vec4 xyzx = U.inner.v.xyzx;
  vec4 xyzy = U.inner.v.xyzy;
  vec4 xyzz = U.inner.v.xyzz;
  vec4 xzxx = U.inner.v.xzxx;
  vec4 xzxy = U.inner.v.xzxy;
  vec4 xzxz = U.inner.v.xzxz;
  vec4 xzyx = U.inner.v.xzyx;
  vec4 xzyy = U.inner.v.xzyy;
  vec4 xzyz = U.inner.v.xzyz;
  vec4 xzzx = U.inner.v.xzzx;
  vec4 xzzy = U.inner.v.xzzy;
  vec4 xzzz = U.inner.v.xzzz;
  vec4 yxxx = U.inner.v.yxxx;
  vec4 yxxy = U.inner.v.yxxy;
  vec4 yxxz = U.inner.v.yxxz;
  vec4 yxyx = U.inner.v.yxyx;
  vec4 yxyy = U.inner.v.yxyy;
  vec4 yxyz = U.inner.v.yxyz;
  vec4 yxzx = U.inner.v.yxzx;
  vec4 yxzy = U.inner.v.yxzy;
  vec4 yxzz = U.inner.v.yxzz;
  vec4 yyxx = U.inner.v.yyxx;
  vec4 yyxy = U.inner.v.yyxy;
  vec4 yyxz = U.inner.v.yyxz;
  vec4 yyyx = U.inner.v.yyyx;
  vec4 yyyy = U.inner.v.yyyy;
  vec4 yyyz = U.inner.v.yyyz;
  vec4 yyzx = U.inner.v.yyzx;
  vec4 yyzy = U.inner.v.yyzy;
  vec4 yyzz = U.inner.v.yyzz;
  vec4 yzxx = U.inner.v.yzxx;
  vec4 yzxy = U.inner.v.yzxy;
  vec4 yzxz = U.inner.v.yzxz;
  vec4 yzyx = U.inner.v.yzyx;
  vec4 yzyy = U.inner.v.yzyy;
  vec4 yzyz = U.inner.v.yzyz;
  vec4 yzzx = U.inner.v.yzzx;
  vec4 yzzy = U.inner.v.yzzy;
  vec4 yzzz = U.inner.v.yzzz;
  vec4 zxxx = U.inner.v.zxxx;
  vec4 zxxy = U.inner.v.zxxy;
  vec4 zxxz = U.inner.v.zxxz;
  vec4 zxyx = U.inner.v.zxyx;
  vec4 zxyy = U.inner.v.zxyy;
  vec4 zxyz = U.inner.v.zxyz;
  vec4 zxzx = U.inner.v.zxzx;
  vec4 zxzy = U.inner.v.zxzy;
  vec4 zxzz = U.inner.v.zxzz;
  vec4 zyxx = U.inner.v.zyxx;
  vec4 zyxy = U.inner.v.zyxy;
  vec4 zyxz = U.inner.v.zyxz;
  vec4 zyyx = U.inner.v.zyyx;
  vec4 zyyy = U.inner.v.zyyy;
  vec4 zyyz = U.inner.v.zyyz;
  vec4 zyzx = U.inner.v.zyzx;
  vec4 zyzy = U.inner.v.zyzy;
  vec4 zyzz = U.inner.v.zyzz;
  vec4 zzxx = U.inner.v.zzxx;
  vec4 zzxy = U.inner.v.zzxy;
  vec4 zzxz = U.inner.v.zzxz;
  vec4 zzyx = U.inner.v.zzyx;
  vec4 zzyy = U.inner.v.zzyy;
  vec4 zzyz = U.inner.v.zzyz;
  vec4 zzzx = U.inner.v.zzzx;
  vec4 zzzy = U.inner.v.zzzy;
  vec4 zzzz = U.inner.v.zzzz;
}

