#version 310 es


struct S {
  ivec3 v;
};

layout(binding = 0, std140)
uniform tint_symbol_1_1_ubo {
  S tint_symbol;
} v_1;
void f() {
  ivec3 v = v_1.tint_symbol.v;
  int x = v_1.tint_symbol.v.x;
  int y = v_1.tint_symbol.v.y;
  int z = v_1.tint_symbol.v.z;
  ivec2 xx = v_1.tint_symbol.v.xx;
  ivec2 xy = v_1.tint_symbol.v.xy;
  ivec2 xz = v_1.tint_symbol.v.xz;
  ivec2 yx = v_1.tint_symbol.v.yx;
  ivec2 yy = v_1.tint_symbol.v.yy;
  ivec2 yz = v_1.tint_symbol.v.yz;
  ivec2 zx = v_1.tint_symbol.v.zx;
  ivec2 zy = v_1.tint_symbol.v.zy;
  ivec2 zz = v_1.tint_symbol.v.zz;
  ivec3 xxx = v_1.tint_symbol.v.xxx;
  ivec3 xxy = v_1.tint_symbol.v.xxy;
  ivec3 xxz = v_1.tint_symbol.v.xxz;
  ivec3 xyx = v_1.tint_symbol.v.xyx;
  ivec3 xyy = v_1.tint_symbol.v.xyy;
  ivec3 xyz = v_1.tint_symbol.v.xyz;
  ivec3 xzx = v_1.tint_symbol.v.xzx;
  ivec3 xzy = v_1.tint_symbol.v.xzy;
  ivec3 xzz = v_1.tint_symbol.v.xzz;
  ivec3 yxx = v_1.tint_symbol.v.yxx;
  ivec3 yxy = v_1.tint_symbol.v.yxy;
  ivec3 yxz = v_1.tint_symbol.v.yxz;
  ivec3 yyx = v_1.tint_symbol.v.yyx;
  ivec3 yyy = v_1.tint_symbol.v.yyy;
  ivec3 yyz = v_1.tint_symbol.v.yyz;
  ivec3 yzx = v_1.tint_symbol.v.yzx;
  ivec3 yzy = v_1.tint_symbol.v.yzy;
  ivec3 yzz = v_1.tint_symbol.v.yzz;
  ivec3 zxx = v_1.tint_symbol.v.zxx;
  ivec3 zxy = v_1.tint_symbol.v.zxy;
  ivec3 zxz = v_1.tint_symbol.v.zxz;
  ivec3 zyx = v_1.tint_symbol.v.zyx;
  ivec3 zyy = v_1.tint_symbol.v.zyy;
  ivec3 zyz = v_1.tint_symbol.v.zyz;
  ivec3 zzx = v_1.tint_symbol.v.zzx;
  ivec3 zzy = v_1.tint_symbol.v.zzy;
  ivec3 zzz = v_1.tint_symbol.v.zzz;
  ivec4 xxxx = v_1.tint_symbol.v.xxxx;
  ivec4 xxxy = v_1.tint_symbol.v.xxxy;
  ivec4 xxxz = v_1.tint_symbol.v.xxxz;
  ivec4 xxyx = v_1.tint_symbol.v.xxyx;
  ivec4 xxyy = v_1.tint_symbol.v.xxyy;
  ivec4 xxyz = v_1.tint_symbol.v.xxyz;
  ivec4 xxzx = v_1.tint_symbol.v.xxzx;
  ivec4 xxzy = v_1.tint_symbol.v.xxzy;
  ivec4 xxzz = v_1.tint_symbol.v.xxzz;
  ivec4 xyxx = v_1.tint_symbol.v.xyxx;
  ivec4 xyxy = v_1.tint_symbol.v.xyxy;
  ivec4 xyxz = v_1.tint_symbol.v.xyxz;
  ivec4 xyyx = v_1.tint_symbol.v.xyyx;
  ivec4 xyyy = v_1.tint_symbol.v.xyyy;
  ivec4 xyyz = v_1.tint_symbol.v.xyyz;
  ivec4 xyzx = v_1.tint_symbol.v.xyzx;
  ivec4 xyzy = v_1.tint_symbol.v.xyzy;
  ivec4 xyzz = v_1.tint_symbol.v.xyzz;
  ivec4 xzxx = v_1.tint_symbol.v.xzxx;
  ivec4 xzxy = v_1.tint_symbol.v.xzxy;
  ivec4 xzxz = v_1.tint_symbol.v.xzxz;
  ivec4 xzyx = v_1.tint_symbol.v.xzyx;
  ivec4 xzyy = v_1.tint_symbol.v.xzyy;
  ivec4 xzyz = v_1.tint_symbol.v.xzyz;
  ivec4 xzzx = v_1.tint_symbol.v.xzzx;
  ivec4 xzzy = v_1.tint_symbol.v.xzzy;
  ivec4 xzzz = v_1.tint_symbol.v.xzzz;
  ivec4 yxxx = v_1.tint_symbol.v.yxxx;
  ivec4 yxxy = v_1.tint_symbol.v.yxxy;
  ivec4 yxxz = v_1.tint_symbol.v.yxxz;
  ivec4 yxyx = v_1.tint_symbol.v.yxyx;
  ivec4 yxyy = v_1.tint_symbol.v.yxyy;
  ivec4 yxyz = v_1.tint_symbol.v.yxyz;
  ivec4 yxzx = v_1.tint_symbol.v.yxzx;
  ivec4 yxzy = v_1.tint_symbol.v.yxzy;
  ivec4 yxzz = v_1.tint_symbol.v.yxzz;
  ivec4 yyxx = v_1.tint_symbol.v.yyxx;
  ivec4 yyxy = v_1.tint_symbol.v.yyxy;
  ivec4 yyxz = v_1.tint_symbol.v.yyxz;
  ivec4 yyyx = v_1.tint_symbol.v.yyyx;
  ivec4 yyyy = v_1.tint_symbol.v.yyyy;
  ivec4 yyyz = v_1.tint_symbol.v.yyyz;
  ivec4 yyzx = v_1.tint_symbol.v.yyzx;
  ivec4 yyzy = v_1.tint_symbol.v.yyzy;
  ivec4 yyzz = v_1.tint_symbol.v.yyzz;
  ivec4 yzxx = v_1.tint_symbol.v.yzxx;
  ivec4 yzxy = v_1.tint_symbol.v.yzxy;
  ivec4 yzxz = v_1.tint_symbol.v.yzxz;
  ivec4 yzyx = v_1.tint_symbol.v.yzyx;
  ivec4 yzyy = v_1.tint_symbol.v.yzyy;
  ivec4 yzyz = v_1.tint_symbol.v.yzyz;
  ivec4 yzzx = v_1.tint_symbol.v.yzzx;
  ivec4 yzzy = v_1.tint_symbol.v.yzzy;
  ivec4 yzzz = v_1.tint_symbol.v.yzzz;
  ivec4 zxxx = v_1.tint_symbol.v.zxxx;
  ivec4 zxxy = v_1.tint_symbol.v.zxxy;
  ivec4 zxxz = v_1.tint_symbol.v.zxxz;
  ivec4 zxyx = v_1.tint_symbol.v.zxyx;
  ivec4 zxyy = v_1.tint_symbol.v.zxyy;
  ivec4 zxyz = v_1.tint_symbol.v.zxyz;
  ivec4 zxzx = v_1.tint_symbol.v.zxzx;
  ivec4 zxzy = v_1.tint_symbol.v.zxzy;
  ivec4 zxzz = v_1.tint_symbol.v.zxzz;
  ivec4 zyxx = v_1.tint_symbol.v.zyxx;
  ivec4 zyxy = v_1.tint_symbol.v.zyxy;
  ivec4 zyxz = v_1.tint_symbol.v.zyxz;
  ivec4 zyyx = v_1.tint_symbol.v.zyyx;
  ivec4 zyyy = v_1.tint_symbol.v.zyyy;
  ivec4 zyyz = v_1.tint_symbol.v.zyyz;
  ivec4 zyzx = v_1.tint_symbol.v.zyzx;
  ivec4 zyzy = v_1.tint_symbol.v.zyzy;
  ivec4 zyzz = v_1.tint_symbol.v.zyzz;
  ivec4 zzxx = v_1.tint_symbol.v.zzxx;
  ivec4 zzxy = v_1.tint_symbol.v.zzxy;
  ivec4 zzxz = v_1.tint_symbol.v.zzxz;
  ivec4 zzyx = v_1.tint_symbol.v.zzyx;
  ivec4 zzyy = v_1.tint_symbol.v.zzyy;
  ivec4 zzyz = v_1.tint_symbol.v.zzyz;
  ivec4 zzzx = v_1.tint_symbol.v.zzzx;
  ivec4 zzzy = v_1.tint_symbol.v.zzzy;
  ivec4 zzzz = v_1.tint_symbol.v.zzzz;
}
layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;
void main() {
}
