#version 310 es


struct S {
  uvec3 v;
};

layout(binding = 0, std140)
uniform tint_symbol_1_1_ubo {
  S tint_symbol;
} v_1;
void f() {
  uvec3 v = v_1.tint_symbol.v;
  uint x = v_1.tint_symbol.v.x;
  uint y = v_1.tint_symbol.v.y;
  uint z = v_1.tint_symbol.v.z;
  uvec2 xx = v_1.tint_symbol.v.xx;
  uvec2 xy = v_1.tint_symbol.v.xy;
  uvec2 xz = v_1.tint_symbol.v.xz;
  uvec2 yx = v_1.tint_symbol.v.yx;
  uvec2 yy = v_1.tint_symbol.v.yy;
  uvec2 yz = v_1.tint_symbol.v.yz;
  uvec2 zx = v_1.tint_symbol.v.zx;
  uvec2 zy = v_1.tint_symbol.v.zy;
  uvec2 zz = v_1.tint_symbol.v.zz;
  uvec3 xxx = v_1.tint_symbol.v.xxx;
  uvec3 xxy = v_1.tint_symbol.v.xxy;
  uvec3 xxz = v_1.tint_symbol.v.xxz;
  uvec3 xyx = v_1.tint_symbol.v.xyx;
  uvec3 xyy = v_1.tint_symbol.v.xyy;
  uvec3 xyz = v_1.tint_symbol.v.xyz;
  uvec3 xzx = v_1.tint_symbol.v.xzx;
  uvec3 xzy = v_1.tint_symbol.v.xzy;
  uvec3 xzz = v_1.tint_symbol.v.xzz;
  uvec3 yxx = v_1.tint_symbol.v.yxx;
  uvec3 yxy = v_1.tint_symbol.v.yxy;
  uvec3 yxz = v_1.tint_symbol.v.yxz;
  uvec3 yyx = v_1.tint_symbol.v.yyx;
  uvec3 yyy = v_1.tint_symbol.v.yyy;
  uvec3 yyz = v_1.tint_symbol.v.yyz;
  uvec3 yzx = v_1.tint_symbol.v.yzx;
  uvec3 yzy = v_1.tint_symbol.v.yzy;
  uvec3 yzz = v_1.tint_symbol.v.yzz;
  uvec3 zxx = v_1.tint_symbol.v.zxx;
  uvec3 zxy = v_1.tint_symbol.v.zxy;
  uvec3 zxz = v_1.tint_symbol.v.zxz;
  uvec3 zyx = v_1.tint_symbol.v.zyx;
  uvec3 zyy = v_1.tint_symbol.v.zyy;
  uvec3 zyz = v_1.tint_symbol.v.zyz;
  uvec3 zzx = v_1.tint_symbol.v.zzx;
  uvec3 zzy = v_1.tint_symbol.v.zzy;
  uvec3 zzz = v_1.tint_symbol.v.zzz;
  uvec4 xxxx = v_1.tint_symbol.v.xxxx;
  uvec4 xxxy = v_1.tint_symbol.v.xxxy;
  uvec4 xxxz = v_1.tint_symbol.v.xxxz;
  uvec4 xxyx = v_1.tint_symbol.v.xxyx;
  uvec4 xxyy = v_1.tint_symbol.v.xxyy;
  uvec4 xxyz = v_1.tint_symbol.v.xxyz;
  uvec4 xxzx = v_1.tint_symbol.v.xxzx;
  uvec4 xxzy = v_1.tint_symbol.v.xxzy;
  uvec4 xxzz = v_1.tint_symbol.v.xxzz;
  uvec4 xyxx = v_1.tint_symbol.v.xyxx;
  uvec4 xyxy = v_1.tint_symbol.v.xyxy;
  uvec4 xyxz = v_1.tint_symbol.v.xyxz;
  uvec4 xyyx = v_1.tint_symbol.v.xyyx;
  uvec4 xyyy = v_1.tint_symbol.v.xyyy;
  uvec4 xyyz = v_1.tint_symbol.v.xyyz;
  uvec4 xyzx = v_1.tint_symbol.v.xyzx;
  uvec4 xyzy = v_1.tint_symbol.v.xyzy;
  uvec4 xyzz = v_1.tint_symbol.v.xyzz;
  uvec4 xzxx = v_1.tint_symbol.v.xzxx;
  uvec4 xzxy = v_1.tint_symbol.v.xzxy;
  uvec4 xzxz = v_1.tint_symbol.v.xzxz;
  uvec4 xzyx = v_1.tint_symbol.v.xzyx;
  uvec4 xzyy = v_1.tint_symbol.v.xzyy;
  uvec4 xzyz = v_1.tint_symbol.v.xzyz;
  uvec4 xzzx = v_1.tint_symbol.v.xzzx;
  uvec4 xzzy = v_1.tint_symbol.v.xzzy;
  uvec4 xzzz = v_1.tint_symbol.v.xzzz;
  uvec4 yxxx = v_1.tint_symbol.v.yxxx;
  uvec4 yxxy = v_1.tint_symbol.v.yxxy;
  uvec4 yxxz = v_1.tint_symbol.v.yxxz;
  uvec4 yxyx = v_1.tint_symbol.v.yxyx;
  uvec4 yxyy = v_1.tint_symbol.v.yxyy;
  uvec4 yxyz = v_1.tint_symbol.v.yxyz;
  uvec4 yxzx = v_1.tint_symbol.v.yxzx;
  uvec4 yxzy = v_1.tint_symbol.v.yxzy;
  uvec4 yxzz = v_1.tint_symbol.v.yxzz;
  uvec4 yyxx = v_1.tint_symbol.v.yyxx;
  uvec4 yyxy = v_1.tint_symbol.v.yyxy;
  uvec4 yyxz = v_1.tint_symbol.v.yyxz;
  uvec4 yyyx = v_1.tint_symbol.v.yyyx;
  uvec4 yyyy = v_1.tint_symbol.v.yyyy;
  uvec4 yyyz = v_1.tint_symbol.v.yyyz;
  uvec4 yyzx = v_1.tint_symbol.v.yyzx;
  uvec4 yyzy = v_1.tint_symbol.v.yyzy;
  uvec4 yyzz = v_1.tint_symbol.v.yyzz;
  uvec4 yzxx = v_1.tint_symbol.v.yzxx;
  uvec4 yzxy = v_1.tint_symbol.v.yzxy;
  uvec4 yzxz = v_1.tint_symbol.v.yzxz;
  uvec4 yzyx = v_1.tint_symbol.v.yzyx;
  uvec4 yzyy = v_1.tint_symbol.v.yzyy;
  uvec4 yzyz = v_1.tint_symbol.v.yzyz;
  uvec4 yzzx = v_1.tint_symbol.v.yzzx;
  uvec4 yzzy = v_1.tint_symbol.v.yzzy;
  uvec4 yzzz = v_1.tint_symbol.v.yzzz;
  uvec4 zxxx = v_1.tint_symbol.v.zxxx;
  uvec4 zxxy = v_1.tint_symbol.v.zxxy;
  uvec4 zxxz = v_1.tint_symbol.v.zxxz;
  uvec4 zxyx = v_1.tint_symbol.v.zxyx;
  uvec4 zxyy = v_1.tint_symbol.v.zxyy;
  uvec4 zxyz = v_1.tint_symbol.v.zxyz;
  uvec4 zxzx = v_1.tint_symbol.v.zxzx;
  uvec4 zxzy = v_1.tint_symbol.v.zxzy;
  uvec4 zxzz = v_1.tint_symbol.v.zxzz;
  uvec4 zyxx = v_1.tint_symbol.v.zyxx;
  uvec4 zyxy = v_1.tint_symbol.v.zyxy;
  uvec4 zyxz = v_1.tint_symbol.v.zyxz;
  uvec4 zyyx = v_1.tint_symbol.v.zyyx;
  uvec4 zyyy = v_1.tint_symbol.v.zyyy;
  uvec4 zyyz = v_1.tint_symbol.v.zyyz;
  uvec4 zyzx = v_1.tint_symbol.v.zyzx;
  uvec4 zyzy = v_1.tint_symbol.v.zyzy;
  uvec4 zyzz = v_1.tint_symbol.v.zyzz;
  uvec4 zzxx = v_1.tint_symbol.v.zzxx;
  uvec4 zzxy = v_1.tint_symbol.v.zzxy;
  uvec4 zzxz = v_1.tint_symbol.v.zzxz;
  uvec4 zzyx = v_1.tint_symbol.v.zzyx;
  uvec4 zzyy = v_1.tint_symbol.v.zzyy;
  uvec4 zzyz = v_1.tint_symbol.v.zzyz;
  uvec4 zzzx = v_1.tint_symbol.v.zzzx;
  uvec4 zzzy = v_1.tint_symbol.v.zzzy;
  uvec4 zzzz = v_1.tint_symbol.v.zzzz;
}
layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;
void main() {
}
