#version 310 es

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;
void unused_entry_point() {
  return;
}
struct S {
  uvec3 v;
  uint pad;
};

layout(binding = 0, std140) uniform U_block_ubo {
  S inner;
} U;

void f() {
  uvec3 v = U.inner.v;
  uint x = U.inner.v.x;
  uint y = U.inner.v.y;
  uint z = U.inner.v.z;
  uvec2 xx = U.inner.v.xx;
  uvec2 xy = U.inner.v.xy;
  uvec2 xz = U.inner.v.xz;
  uvec2 yx = U.inner.v.yx;
  uvec2 yy = U.inner.v.yy;
  uvec2 yz = U.inner.v.yz;
  uvec2 zx = U.inner.v.zx;
  uvec2 zy = U.inner.v.zy;
  uvec2 zz = U.inner.v.zz;
  uvec3 xxx = U.inner.v.xxx;
  uvec3 xxy = U.inner.v.xxy;
  uvec3 xxz = U.inner.v.xxz;
  uvec3 xyx = U.inner.v.xyx;
  uvec3 xyy = U.inner.v.xyy;
  uvec3 xyz = U.inner.v.xyz;
  uvec3 xzx = U.inner.v.xzx;
  uvec3 xzy = U.inner.v.xzy;
  uvec3 xzz = U.inner.v.xzz;
  uvec3 yxx = U.inner.v.yxx;
  uvec3 yxy = U.inner.v.yxy;
  uvec3 yxz = U.inner.v.yxz;
  uvec3 yyx = U.inner.v.yyx;
  uvec3 yyy = U.inner.v.yyy;
  uvec3 yyz = U.inner.v.yyz;
  uvec3 yzx = U.inner.v.yzx;
  uvec3 yzy = U.inner.v.yzy;
  uvec3 yzz = U.inner.v.yzz;
  uvec3 zxx = U.inner.v.zxx;
  uvec3 zxy = U.inner.v.zxy;
  uvec3 zxz = U.inner.v.zxz;
  uvec3 zyx = U.inner.v.zyx;
  uvec3 zyy = U.inner.v.zyy;
  uvec3 zyz = U.inner.v.zyz;
  uvec3 zzx = U.inner.v.zzx;
  uvec3 zzy = U.inner.v.zzy;
  uvec3 zzz = U.inner.v.zzz;
  uvec4 xxxx = U.inner.v.xxxx;
  uvec4 xxxy = U.inner.v.xxxy;
  uvec4 xxxz = U.inner.v.xxxz;
  uvec4 xxyx = U.inner.v.xxyx;
  uvec4 xxyy = U.inner.v.xxyy;
  uvec4 xxyz = U.inner.v.xxyz;
  uvec4 xxzx = U.inner.v.xxzx;
  uvec4 xxzy = U.inner.v.xxzy;
  uvec4 xxzz = U.inner.v.xxzz;
  uvec4 xyxx = U.inner.v.xyxx;
  uvec4 xyxy = U.inner.v.xyxy;
  uvec4 xyxz = U.inner.v.xyxz;
  uvec4 xyyx = U.inner.v.xyyx;
  uvec4 xyyy = U.inner.v.xyyy;
  uvec4 xyyz = U.inner.v.xyyz;
  uvec4 xyzx = U.inner.v.xyzx;
  uvec4 xyzy = U.inner.v.xyzy;
  uvec4 xyzz = U.inner.v.xyzz;
  uvec4 xzxx = U.inner.v.xzxx;
  uvec4 xzxy = U.inner.v.xzxy;
  uvec4 xzxz = U.inner.v.xzxz;
  uvec4 xzyx = U.inner.v.xzyx;
  uvec4 xzyy = U.inner.v.xzyy;
  uvec4 xzyz = U.inner.v.xzyz;
  uvec4 xzzx = U.inner.v.xzzx;
  uvec4 xzzy = U.inner.v.xzzy;
  uvec4 xzzz = U.inner.v.xzzz;
  uvec4 yxxx = U.inner.v.yxxx;
  uvec4 yxxy = U.inner.v.yxxy;
  uvec4 yxxz = U.inner.v.yxxz;
  uvec4 yxyx = U.inner.v.yxyx;
  uvec4 yxyy = U.inner.v.yxyy;
  uvec4 yxyz = U.inner.v.yxyz;
  uvec4 yxzx = U.inner.v.yxzx;
  uvec4 yxzy = U.inner.v.yxzy;
  uvec4 yxzz = U.inner.v.yxzz;
  uvec4 yyxx = U.inner.v.yyxx;
  uvec4 yyxy = U.inner.v.yyxy;
  uvec4 yyxz = U.inner.v.yyxz;
  uvec4 yyyx = U.inner.v.yyyx;
  uvec4 yyyy = U.inner.v.yyyy;
  uvec4 yyyz = U.inner.v.yyyz;
  uvec4 yyzx = U.inner.v.yyzx;
  uvec4 yyzy = U.inner.v.yyzy;
  uvec4 yyzz = U.inner.v.yyzz;
  uvec4 yzxx = U.inner.v.yzxx;
  uvec4 yzxy = U.inner.v.yzxy;
  uvec4 yzxz = U.inner.v.yzxz;
  uvec4 yzyx = U.inner.v.yzyx;
  uvec4 yzyy = U.inner.v.yzyy;
  uvec4 yzyz = U.inner.v.yzyz;
  uvec4 yzzx = U.inner.v.yzzx;
  uvec4 yzzy = U.inner.v.yzzy;
  uvec4 yzzz = U.inner.v.yzzz;
  uvec4 zxxx = U.inner.v.zxxx;
  uvec4 zxxy = U.inner.v.zxxy;
  uvec4 zxxz = U.inner.v.zxxz;
  uvec4 zxyx = U.inner.v.zxyx;
  uvec4 zxyy = U.inner.v.zxyy;
  uvec4 zxyz = U.inner.v.zxyz;
  uvec4 zxzx = U.inner.v.zxzx;
  uvec4 zxzy = U.inner.v.zxzy;
  uvec4 zxzz = U.inner.v.zxzz;
  uvec4 zyxx = U.inner.v.zyxx;
  uvec4 zyxy = U.inner.v.zyxy;
  uvec4 zyxz = U.inner.v.zyxz;
  uvec4 zyyx = U.inner.v.zyyx;
  uvec4 zyyy = U.inner.v.zyyy;
  uvec4 zyyz = U.inner.v.zyyz;
  uvec4 zyzx = U.inner.v.zyzx;
  uvec4 zyzy = U.inner.v.zyzy;
  uvec4 zyzz = U.inner.v.zyzz;
  uvec4 zzxx = U.inner.v.zzxx;
  uvec4 zzxy = U.inner.v.zzxy;
  uvec4 zzxz = U.inner.v.zzxz;
  uvec4 zzyx = U.inner.v.zzyx;
  uvec4 zzyy = U.inner.v.zzyy;
  uvec4 zzyz = U.inner.v.zzyz;
  uvec4 zzzx = U.inner.v.zzzx;
  uvec4 zzzy = U.inner.v.zzzy;
  uvec4 zzzz = U.inner.v.zzzz;
}

