# Copyright 2023 The Tint Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

################################################################################
# File generated by tools/src/cmd/gen
# using the template:
#   tools/src/cmd/gen/build/BUILD.cmake.tmpl
#
# Do not modify this file directly
################################################################################

tint_add_target("lang/core/constant"
  lang/core/constant/clone_context.h
  lang/core/constant/composite.cc
  lang/core/constant/composite.h
  lang/core/constant/eval.cc
  lang/core/constant/eval.h
  lang/core/constant/manager.cc
  lang/core/constant/manager.h
  lang/core/constant/node.cc
  lang/core/constant/node.h
  lang/core/constant/scalar.cc
  lang/core/constant/scalar.h
  lang/core/constant/splat.cc
  lang/core/constant/splat.h
  lang/core/constant/value.cc
  lang/core/constant/value.h
)

tint_target_add_dependencies("lang/core/constant"
  "lang/core"
  "lang/core/type"
  "utils/containers"
  "utils/diagnostic"
  "utils/ice"
  "utils/id"
  "utils/macros"
  "utils/math"
  "utils/memory"
  "utils/result"
  "utils/rtti"
  "utils/symbol"
  "utils/text"
  "utils/traits"
)

tint_add_target("lang/core/constant:test"
  lang/core/constant/composite_test.cc
  lang/core/constant/eval_binary_op_test.cc
  lang/core/constant/eval_bitcast_test.cc
  lang/core/constant/eval_builtin_test.cc
  lang/core/constant/eval_construction_test.cc
  lang/core/constant/eval_conversion_test.cc
  lang/core/constant/eval_indexing_test.cc
  lang/core/constant/eval_member_access_test.cc
  lang/core/constant/eval_runtime_semantics_test.cc
  lang/core/constant/eval_test.h
  lang/core/constant/eval_unary_op_test.cc
  lang/core/constant/helper_test.h
  lang/core/constant/manager_test.cc
  lang/core/constant/scalar_test.cc
  lang/core/constant/splat_test.cc
  lang/core/constant/value_test.cc
)

tint_target_add_dependencies("lang/core/constant:test"
  "api/common"
  "lang/core"
  "lang/core/constant"
  "lang/core/intrinsic"
  "lang/core/type"
  "lang/core/type:test"
  "lang/wgsl/ast"
  "lang/wgsl/program"
  "lang/wgsl/reader"
  "lang/wgsl/resolver"
  "lang/wgsl/resolver:test"
  "lang/wgsl/sem"
  "utils/containers"
  "utils/diagnostic"
  "utils/ice"
  "utils/id"
  "utils/macros"
  "utils/math"
  "utils/memory"
  "utils/reflection"
  "utils/result"
  "utils/rtti"
  "utils/symbol"
  "utils/text"
  "utils/traits"
)
