// Copyright 2025 The Dawn & Tint Authors
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions are met:
//
// 1. Redistributions of source code must retain the above copyright notice, this
//    list of conditions and the following disclaimer.
//
// 2. Redistributions in binary form must reproduce the above copyright notice,
//    this list of conditions and the following disclaimer in the documentation
//    and/or other materials provided with the distribution.
//
// 3. Neither the name of the copyright holder nor the names of its
//    contributors may be used to endorse or promote products derived from
//    this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
// AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
// IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
// DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
// FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
// DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
// SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
// CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
// OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

////////////////////////////////////////////////////////////////////////////////
// File generated by 'tools/src/cmd/gen' using the template:
//   src/tint/cmd/bench/enums_wgsl_bench.cc.tmpl
//
// To regenerate run: './tools/run gen'
//
//                       Do not modify this file directly
////////////////////////////////////////////////////////////////////////////////

// clang-format off

#include <array>

#include "benchmark/benchmark.h"
#include "src/tint/lang/wgsl/enums.h"

namespace tint::wgsl {
namespace {

void CoreDiagnosticRuleParser(::benchmark::State& state) {
    const char* kStrings[] = {
        "deriative_unccformity",
        "dlivative_3iformiy",
        "derivative_uniforVity",
        "derivative_uniformity",
        "derivative_uniform1ty",
        "derivativeJunifqrmity",
        "derivative_unifllrmit77",
        "subgopppqquniformitHH",
        "subgrou_cformity",
        "subgGoup_unifombty",
        "subgroup_uniformity",
        "suvgroup_uniformiiiy",
        "subgroWWp8uniformity",
        "subgroup_uifoxxmiMy",
    };
    for (auto _ : state) {
        for (auto* str : kStrings) {
            auto result = ParseCoreDiagnosticRule(str);
            benchmark::DoNotOptimize(result);
        }
    }
}  // NOLINT(readability/fn_size)

BENCHMARK(CoreDiagnosticRuleParser);
void ChromiumDiagnosticRuleParser(::benchmark::State& state) {
    const char* kStrings[] = {
        "sbgroup_ggatrix_uniformXty",
        "suVroup_matrx_uniforXitu",
        "subgroup_ma3rix_uniformity",
        "subgroup_matrix_uniformity",
        "subgroup_matrix_uniformitE",
        "subgroup_atrix_uniTTPormity",
        "suxxdgroup_matri_uniformity",
        "44nreachable_code",
        "unreaVVhabSSe_code",
        "unre22chabR_Rode",
        "unreachable_code",
        "nFeachable_9ode",
        "unrachable_code",
        "VnreacaRRlH_OOode",
    };
    for (auto _ : state) {
        for (auto* str : kStrings) {
            auto result = ParseChromiumDiagnosticRule(str);
            benchmark::DoNotOptimize(result);
        }
    }
}  // NOLINT(readability/fn_size)

BENCHMARK(ChromiumDiagnosticRuleParser);
void DiagnosticSeverityParser(::benchmark::State& state) {
    const char* kStrings[] = {
        "rryr",
        "n77rrlrGr",
        "erro40",
        "error",
        "oor",
        "erzz",
        "1ippor",
        "XXnfo",
        "55nII9nn",
        "iSSfHHaa",
        "info",
        "kk",
        "gRR",
        "ib",
        "ojf",
        "of",
        "q",
        "off",
        "oNN",
        "ov",
        "Qff",
        "waffir",
        "warnijg",
        "wNNwnin8",
        "warning",
        "waring",
        "wrrrning",
        "Garning",
    };
    for (auto _ : state) {
        for (auto* str : kStrings) {
            auto result = ParseDiagnosticSeverity(str);
            benchmark::DoNotOptimize(result);
        }
    }
}  // NOLINT(readability/fn_size)

BENCHMARK(DiagnosticSeverityParser);
void ExtensionParser(::benchmark::State& state) {
    const char* kStrings[] = {
        "chromium_disable_uniformity_analyFFis",
        "chromium_diEabl_uniformty_analyis",
        "crrromium_diable_uniformity_analysis",
        "chromium_disable_uniformity_analysis",
        "chromiumdisabl_uniformity_analysis",
        "chromium_JJXDabe_uniformity_analysis",
        "8hromium_isable_uiformiy_analysis",
        "chromium_experim1kntalbrycenric_coord",
        "chromium_experimentalbarycentric_coord",
        "chJomium_experimental_barycentric_coor",
        "chromium_experimental_barycentric_coord",
        "chromium_experimencal_barycentric_coord",
        "chromium_experimental_Oarycentric_coord",
        "chrttmium_experimental_bv__rycentric_KKoord",
        "chrxxmium_8perimental_dynamic_5inding",
        "__hromFumexperimental_ynqqmic_binding",
        "chromium_xperimentqql_dynamic_binding",
        "chromium_experimental_dynamic_binding",
        "chromum_experim33ntal_dynam66c_biOding",
        "chromium_QQxperimental_6y9amic_ttoonding",
        "chromium_experimenta_dynamic_bin66ing",
        "hromxum_experimental_zzr66mebufferOfetch",
        "chromium_experimental_framebyyffer_fetch",
        "chrmium_experimental_fraeHHuffer_feZch",
        "chromium_experimental_framebuffer_fetch",
        "chromium_expeimeWWtal_framebuq4fer_fetch",
        "chromium_experimental_fOOamebuffer_etch",
        "chroomium_experimntalhframebuffr_fetcY",
        "chomium_experiental_pixel_loca",
        "chromum_experimental_pixel_lFcal",
        "chromium_expewimentalpixel_local",
        "chromium_experimental_pixel_local",
        "chromffum_expeKmentG_pixel_local",
        "chromiuq_KKxperimental_pixel_local",
        "chromium_eFpe3imental_mmixel_local",
        "chromium_experimental_reource_table",
        "chromium_experimentalresourcq_table",
        "chromium_ebbprimental_resource_table",
        "chromium_experimental_resource_table",
        "chromium_expirimental_resource_tabe",
        "chromium_experimentl_resoOOrce_tablq",
        "chromium_experimental_TTvvsource_table",
        "chromium_experimental_subgrouFF_matrix",
        "chromifm_experimenta00PsubgroQp_mtrix",
        "chromium_experPmental_subgroup_matrix",
        "chromium_experimental_subgroup_matrix",
        "cssomium_experimental_subgroup_mat77ix",
        "chromium_exbberimenCal_subgroup_mRRtrix",
        "chromium_experimental_subgroup_mXXtrix",
        "chromium_expqrimental_CCubgOOoup_size_OOontol",
        "chromim_experimentaL_subgroup_size_contuol",
        "chromiuX_experimental_subgroup_size_control",
        "chromium_experimental_subgroup_size_control",
        "chromium_experimental_subgroup_size_contol",
        "chromium_exerimentlqqsubgroup_size_ontOol",
        "chromium_experimental_subgroup_size_contr22l",
        "chromiuXX_interzza_graphity",
        "chromPum_internal_grapVite",
        "chromum_internal_grCphitnn",
        "chromium_internal_graphite",
        "chromium_nqqeAAnal_gHHphite",
        "chromium_interal_graphite",
        "chrmium_intfrnl_graphitKK",
        "chromiul_intenal_inggut_Pttachmets",
        "chromium_internal_input_attachmens",
        "cTTrom4uc_internal_input_attachmNnts",
        "chromium_internal_input_attachments",
        "phromium_77nternal_input_attalhments",
        "chromium_inteNNzzl_npug_attachments",
        "chromim_intXXrnal_inpuutatbbachments",
        "cli_distances",
        "cliK_diQa88es",
        "cli9_qisances",
        "clip_distances",
        "clip_dis11ances",
        "clip_ds22Fniies",
        "clip_distnce77",
        "du2_source_blenNNing",
        "dual_source_blenVVing",
        "WW11al_sourcewblenFing",
        "dual_source_blending",
        "dual_souwwceblending",
        "dual_sDurce_blending",
        "duKl_souce_blending",
        "1PP1h",
        "f1",
        "f1YY",
        "f16",
        "1tkk",
        "rr16",
        "fWW6",
        "prmitive_iYdex",
        "primfLiqe_ndex",
        "vvrmitive_22nduux",
        "primitive_index",
        "piitive_index",
        "primtive_indeY",
        "pEimityYYe_inde77",
        "Muoodrous",
        "subMMrous",
        "subgrou55s",
        "subgroups",
        "Ngroups",
        "subgro33p",
        "subgroup3",
    };
    for (auto _ : state) {
        for (auto* str : kStrings) {
            auto result = ParseExtension(str);
            benchmark::DoNotOptimize(result);
        }
    }
}  // NOLINT(readability/fn_size)

BENCHMARK(ExtensionParser);

}  // namespace
}  // namespace tint::wgsl

// clang-format on
