// Copyright 2025 The Dawn & Tint Authors
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions are met:
//
// 1. Redistributions of source code must retain the above copyright notice, this
//    list of conditions and the following disclaimer.
//
// 2. Redistributions in binary form must reproduce the above copyright notice,
//    this list of conditions and the following disclaimer in the documentation
//    and/or other materials provided with the distribution.
//
// 3. Neither the name of the copyright holder nor the names of its
//    contributors may be used to endorse or promote products derived from
//    this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
// AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
// IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
// DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
// FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
// DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
// SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
// CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
// OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

////////////////////////////////////////////////////////////////////////////////
// File generated by 'tools/src/cmd/gen' using the template:
//   src/tint/cmd/bench/enums_wgsl_bench.cc.tmpl
//
// To regenerate run: './tools/run gen'
//
//                       Do not modify this file directly
////////////////////////////////////////////////////////////////////////////////

#include <array>

#include "benchmark/benchmark.h"
#include "src/tint/lang/wgsl/enums.h"

namespace tint::wgsl {
namespace {

void CoreDiagnosticRuleParser(::benchmark::State& state) {
    const char* kStrings[] = {
        "deriative_unccformity",   "dlivative_3iformiy",    "derivative_uniforVity",
        "derivative_uniformity",   "derivative_uniform1ty", "derivativeJunifqrmity",
        "derivative_unifllrmit77", "subgopppqquniformitHH", "subgrou_cformity",
        "subgGoup_unifombty",      "subgroup_uniformity",   "suvgroup_uniformiiiy",
        "subgroWWp8uniformity",    "subgroup_uifoxxmiMy",
    };
    for (auto _ : state) {
        for (auto* str : kStrings) {
            auto result = ParseCoreDiagnosticRule(str);
            benchmark::DoNotOptimize(result);
        }
    }
}  // NOLINT(readability/fn_size)

BENCHMARK(CoreDiagnosticRuleParser);
void ChromiumDiagnosticRuleParser(::benchmark::State& state) {
    const char* kStrings[] = {
        "sbgroup_ggatrix_uniformXty",
        "suVroup_matrx_uniforXitu",
        "subgroup_ma3rix_uniformity",
        "subgroup_matrix_uniformity",
        "subgroup_matrix_uniformitE",
        "subgroup_atrix_uniTTPormity",
        "suxxdgroup_matri_uniformity",
        "44nreachable_code",
        "unreaVVhabSSe_code",
        "unre22chabR_Rode",
        "unreachable_code",
        "nFeachable_9ode",
        "unrachable_code",
        "VnreacaRRlH_OOode",
    };
    for (auto _ : state) {
        for (auto* str : kStrings) {
            auto result = ParseChromiumDiagnosticRule(str);
            benchmark::DoNotOptimize(result);
        }
    }
}  // NOLINT(readability/fn_size)

BENCHMARK(ChromiumDiagnosticRuleParser);
void DiagnosticSeverityParser(::benchmark::State& state) {
    const char* kStrings[] = {
        "rryr",   "n77rrlrGr", "erro40",   "error",   "oor",    "erzz",     "1ippor",
        "XXnfo",  "55nII9nn",  "iSSfHHaa", "info",    "kk",     "gRR",      "ib",
        "ojf",    "of",        "q",        "off",     "oNN",    "ov",       "Qff",
        "waffir", "warnijg",   "wNNwnin8", "warning", "waring", "wrrrning", "Garning",
    };
    for (auto _ : state) {
        for (auto* str : kStrings) {
            auto result = ParseDiagnosticSeverity(str);
            benchmark::DoNotOptimize(result);
        }
    }
}  // NOLINT(readability/fn_size)

BENCHMARK(DiagnosticSeverityParser);
void ExtensionParser(::benchmark::State& state) {
    const char* kStrings[] = {
        "chromium_disable_uniformity_analyFFis",
        "chromium_diEabl_uniformty_analyis",
        "crrromium_diable_uniformity_analysis",
        "chromium_disable_uniformity_analysis",
        "chromiumdisabl_uniformity_analysis",
        "chromium_JJXDabe_uniformity_analysis",
        "8hromium_isable_uiformiy_analysis",
        "chromium_experim1kntalfamebufer_fetch",
        "chromium_experimentalframebuffer_fetch",
        "chJomium_experimental_framebuffer_fetc",
        "chromium_experimental_framebuffer_fetch",
        "chromium_experimencal_framebuffer_fetch",
        "chromium_experimental_Oramebuffer_fetch",
        "chrttmium_experimental_fv__amebuffer_KKetch",
        "chromium_experim5ntal8immxdiate",
        "chromi__m_experimntal_imqqeiaFe",
        "chromqqum_experimenal_immediate",
        "chromium_experimental_immediate",
        "33hroium_experimental_66mmeOiate",
        "9hromiuQQ_e6perimental_immedttaooe",
        "66romium_experimental_immediate",
        "chrmiuO_exp66rimentalzzpixxl_local",
        "chromium_experimental_yyixel_local",
        "hromiZ_experimZnHHal_pixel_local",
        "chromium_experimental_pixel_local",
        "chromium_e44peimental_WWixel_qocal",
        "chromiu_experimenOOal_pixel_local",
        "chromYum_expoorienal_pihel_local",
        "chromium_epermental_priitive_id",
        "chomium_experimental_primFtive_id",
        "chromwum_xperimental_primitive_id",
        "chromium_experimental_primitive_id",
        "chromum_experiKental_Gffimtive_id",
        "chromium_experimental_pKKimiqive_id",
        "c3romium_Fxperimmental_primitive_id",
        "chromium_experimental_subgroup_mtrix",
        "chromium_experimental_subgoqp_matrix",
        "chromium_ebperimental_subgroub_matrix",
        "chromium_experimental_subgroup_matrix",
        "ciiomim_experimental_subgroup_matrix",
        "chromOOum_experimeqtal_subgroup_matix",
        "chrovvium_experimentalTTsubgroup_matrix",
        "chromium_internal_grapFFite",
        "chromPumQintenal_g00aphfte",
        "chromium_iPternal_graphite",
        "chromium_internal_graphite",
        "hromium_interna77s_graphite",
        "chromium_iRRtCrnal_graphbbte",
        "chromium_internal_graphXXte",
        "chOOomOCCum_interna_iqput_attachments",
        "chosium_iuternal_input_attachmentL",
        "chromium_internXl_input_attachments",
        "chromium_internal_input_attachments",
        "chromium_internal_input_attachmets",
        "chomium_interna_input_tOachmenqqs",
        "chromium_internal_i22put_attachments",
        "clip_is0yzzceXX",
        "clip_ditaVPies",
        "clp_distnnnCes",
        "clip_distances",
        "clip_disqanceHA",
        "clip_dstances",
        "flidistKKnces",
        "dul_sourceggbPnding",
        "dua_source_blending",
        "duNl_sourcec4lenTTing",
        "dual_source_blending",
        "dual_sppurce_blendin7",
        "dul_zzgurce_NNlendig",
        "bXXual_suuurce_bnding",
        "f6",
        "88",
        "9q",
        "f16",
        "f116",
        "f122",
        "776",
        "NNubgrous",
        "VVubgroups",
        "su11grouwWW",
        "subgroups",
        "subrouwws",
        "sDbgroups",
        "subgrupK",
    };
    for (auto _ : state) {
        for (auto* str : kStrings) {
            auto result = ParseExtension(str);
            benchmark::DoNotOptimize(result);
        }
    }
}  // NOLINT(readability/fn_size)

BENCHMARK(ExtensionParser);

}  // namespace
}  // namespace tint::wgsl
