// Copyright 2021 The Tint Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

////////////////////////////////////////////////////////////////////////////////
// File generated by tools/src/cmd/gen
// using the template:
//   src/tint/lang/core/intrinsic/ctor_conv.cc.tmpl
//
// Do not modify this file directly
////////////////////////////////////////////////////////////////////////////////

#include "src/tint/lang/core/intrinsic/ctor_conv.h"

namespace tint::core::intrinsic {

const char* str(CtorConv i) {
    switch (i) {
        case CtorConv::kNone:
            return "<none>";
        case CtorConv::kI32:
            return "i32";
        case CtorConv::kU32:
            return "u32";
        case CtorConv::kF32:
            return "f32";
        case CtorConv::kF16:
            return "f16";
        case CtorConv::kBool:
            return "bool";
        case CtorConv::kVec2:
            return "vec2";
        case CtorConv::kVec3:
            return "vec3";
        case CtorConv::kVec4:
            return "vec4";
        case CtorConv::kMat2x2:
            return "mat2x2";
        case CtorConv::kMat2x3:
            return "mat2x3";
        case CtorConv::kMat2x4:
            return "mat2x4";
        case CtorConv::kMat3x2:
            return "mat3x2";
        case CtorConv::kMat3x3:
            return "mat3x3";
        case CtorConv::kMat3x4:
            return "mat3x4";
        case CtorConv::kMat4x2:
            return "mat4x2";
        case CtorConv::kMat4x3:
            return "mat4x3";
        case CtorConv::kMat4x4:
            return "mat4x4";
        case CtorConv::kPackedVec3:
            return "packedVec3";
    }
    return "<unknown>";
}

}  // namespace tint::core::intrinsic
