#!/usr/bin/env python3
# Copyright 2026 The Dawn & Tint Authors
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this
#    list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
#
# 3. Neither the name of the copyright holder nor the names of its
#    contributors may be used to endorse or promote products derived from
#    this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

import argparse
import json
import sys
import subprocess
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
DAWN_ROOT = SCRIPT_DIR.parent


def fail(message: str) -> None:
    print(message, file=sys.stderr)
    sys.exit(1)


def is_generated_file(file_path: Path) -> bool:
    return file_path.is_relative_to(DAWN_ROOT / "out")


def find_latest_findings_file() -> Path:
    # Look for clang-tidy-*-findings.json (generated by tools/run-tricium-clang-tidy.py)
    # in the current working directory.
    findings_files = sorted(Path.cwd().glob("clang-tidy-*-findings.json"))
    if not findings_files:
        fail(
            "Error: No clang-tidy-*-findings.json found in the current directory.\n"
            "Please run tools/run-tricium-clang-tidy.py first to generate findings, or specify --findings."
        )
    return findings_files[-1]


def main():
    if Path.cwd().resolve() != DAWN_ROOT.resolve():
        fail("Error: must be run from the Dawn root directory.")

    parser = argparse.ArgumentParser(
        description=
        "Extract files matching a given clang-tidy check from findings.json and apply autofixes. "
        "Note findings.json is only used to determine which files to inspect - this script applies ALL fixes for that check in the file, regardless of the exact fixits listed in findings.json.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    # Build directory (Required positional argument to match tools/run-tricium-clang-tidy.py)
    parser.add_argument("outdir", help="The build directory, e.g., out/tidy")
    parser.add_argument(
        "files",
        nargs="*",
        help=
        "Apply fixes only to the specified files, for example `src/dawn/**/*`.",
    )
    parser.add_argument(
        "-c",
        "--check",
        required=True,
        help=
        "The specific clang-tidy check to apply fixes for (e.g., bugprone-parent-virtual-call)."
    )
    parser.add_argument(
        "-f",
        "--findings",
        help=
        "Path to the findings JSON file. If not specified, the latest clang-tidy-*-findings.json file is used."
    )

    args = parser.parse_args()

    # Determine findings file path
    if args.findings:
        findings_path = Path(args.findings)
        if not findings_path.is_file():
            fail(f"Error: Findings file not found: {findings_path}")
    else:
        findings_path = find_latest_findings_file()

    print(f"Reading findings from: {findings_path}")

    # Parse findings JSON
    try:
        with open(findings_path, "r", encoding="utf-8") as f:
            data = json.load(f)
    except Exception as e:
        fail(f"Error parsing findings JSON file {findings_path}: {e}")

    if args.files:
        enabled_files = {(DAWN_ROOT / f).resolve() for f in args.files}
        is_target_file = lambda file_path: file_path.resolve() in enabled_files
    else:
        is_target_file = lambda file_path: not is_generated_file(file_path)

    # Extract matching files
    files_to_fix = set()
    diagnostics = data.get("diagnostics", [])
    for diag in diagnostics:
        if diag.get("diag_name") == args.check:
            file_path_str = diag.get("file_path")
            if file_path_str:
                file_path = DAWN_ROOT / file_path_str
                if is_target_file(file_path):
                    files_to_fix.add(file_path.relative_to(DAWN_ROOT))

    if not files_to_fix:
        if args.files:
            print(f"No diagnostics found matching check "
                  "(in specified fileset): '{args.check}'")
        else:
            print(f"No diagnostics found matching check "
                  "(in non-generated files): '{args.check}'")
        return

    print(f"Found {len(files_to_fix)} file(s) with diagnostics for "
          "'{args.check}':")
    for file in sorted(files_to_fix):
        print(f"  {file}")

    # Locate clang-tidy binary
    clang_tidy = Path("third_party/llvm-build/Release+Asserts/bin/clang-tidy")
    if sys.platform == "win32":
        clang_tidy = clang_tidy.with_suffix(".exe")

    if not clang_tidy.is_file():
        fail(f'{clang_tidy} missing. See docs/clang-tidy.md.')

    # Validate build directory
    outdir_path = Path(args.outdir)
    if not outdir_path.is_dir() or not (outdir_path /
                                        "compile_commands.json").is_file():
        fail(f"Error: Build directory '{args.outdir}' does not exist or lacks "
             "compile_commands.json.")

    # Assemble and run the command
    cmd = [
        str(clang_tidy),
        f"-p={outdir_path}",
        f"-checks=-*,{args.check}",
        "--fix",
        # Disable compiler warnings because they prevent clang-tidy from working
        "--extra-arg=-w",
    ] + [str(f) for f in sorted(files_to_fix)]

    print(f"\nRunning command:\n  {' '.join(cmd)}")
    try:
        subprocess.run(cmd, check=True)
        print("\nFixes successfully applied!")
    except subprocess.CalledProcessError as e:
        fail(f"\nClang-tidy failed with exit code {e.returncode}")


if __name__ == "__main__":
    main()
