#!/bin/bash
# Copyright 2022 The Tint Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# If there are files in the repo with CRLF endings, then they will be printed
# and the script will exit with 1. If there are no files with CRLF endings, then
# the script will print nothing and will exit with 0.

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd )"
ROOT_DIR="$( cd "${SCRIPT_DIR}/.." >/dev/null 2>&1 && pwd )"
CRLF_FILES=$(git -C ${ROOT_DIR} grep -I --files-with-matches --perl-regexp '\r' .)
if [ ! -z ${CRLF_FILES} ]; then
  echo "The following files contain CRLF characters:"
  echo ${CRLF_FILES}
  exit 1
fi
