#!/bin/bash
# Copyright 2020 The Tint Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd )"
ROOT_DIR="$( cd "${SCRIPT_DIR}/.." >/dev/null 2>&1 && pwd )"

set -e  # fail on error

if ! command -v cpplint.py &> /dev/null; then
    echo "cpplint.py not found on PATH"
    exit 1
fi

FILTER="-runtime/references"

FILES=""
FILES+="`find src/tint -type f` "
FILES+="`find src/tint/cmd -type f` "
FILES+="`find tools/src -type f` "
FILES+="`find src/tint/cmd -type f` "

# Note, there is currently no verbosity level set for cpplint.py which means
# it will use the default level of 1. This level needs to match what is in the
# PRESUBMIT.py file in order to report the same errors between CQ and Kokoro.

if command -v go &> /dev/null; then
    # Go is installed. Run cpplint in parallel for speed wins
    ${SCRIPT_DIR}/run run-parallel                  \
         --only-print-failures                      \
         cpplint.py                                 \
         --root=$ROOT_DIR                           \
         --filter="$FILTER"                         \
         $ -- $FILES
else
    cpplint.py --root=$ROOT_DIR --filter="$FILTER" $FILES
fi

