name: On copybara import

on:
  pull_request:
    branches: [ "main" ]
  check_run:
    types:
      - completed
  check_suite:
    types:
      - completed

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  comment2:
    name: comment2
    runs-on: ubuntu-latest
    steps:
    - uses: actions/github-script@v6
      name: Test check_suite event
      with:
        script: |
          console.log(github.event.check_suite)

  comment:
    name: comment
    if: github.event.check_run.name == 'import/copybara' && github.event.check_run.conclusion == 'success' && github.event.check_run.pull_requests[0]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/github-script@v6
      name: Comment on PR
      with:
        script: |
          console.log(github.event.check_run)
          github.rest.issues.createComment({
            issue_number: github.event.check_run.pull_requests[0].number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: |
              👋 Thanks for your contribution! Your PR has been imported to Gerrit.
              Please visit ${{ github.event.check_run.details_url }} to see it and CC yourself on the change.
              All comments are handled within Gerrit. Any comments on the GitHub PR may be ignored.
              You can continue to upload commits to the PR in order to address feedback from Gerrit.
          })
