name: On copybara import

on:
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]
  check_run:
    types:
      - completed

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  comment_test:
    name: comment test
    if: github.event.pull_request.number
    runs-on: ubuntu-latest
    steps:
    - name: Wait for import/copybara
      uses: lewagon/wait-on-check-action@v1.3.1
      with:
        ref: ${{ github.ref }}
        check-name: 'import/copybara'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        wait-interval: 10
    - uses: actions/github-script@v6
      name: Comment on PR
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: github.event.pull_request.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: |
              👋 Thanks for your contribution! Your PR has been imported to Gerrit.
              Please visit Gerrit to see it and CC yourself on the change.
              All comments are handled within Gerrit. Any comments on the GitHub PR may be ignored.
              You can continue to upload commits to the PR in order to address feedback from Gerrit.
          })

  comment:
    name: comment
    if: github.event.check_run.name == 'import/copybara' && github.event.check_run.conclusion == 'success' && github.event.check_run.pull_requests[0]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/github-script@v6
      name: Comment on PR
      with:
        script: |
          console.log(github.event.check_run)
          github.rest.issues.createComment({
            issue_number: github.event.check_run.pull_requests[0].number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: |
              👋 Thanks for your contribution! Your PR has been imported to Gerrit.
              Please visit ${{ github.event.check_run.details_url }} to see it and CC yourself on the change.
              All comments are handled within Gerrit. Any comments on the GitHub PR may be ignored.
              You can continue to upload commits to the PR in order to address feedback from Gerrit.
          })
