name: release

on:
  workflow_dispatch:
    inputs:
      commit_hash:
        description: 'The specific Dawn commit hash to checkout and build'
        required: true
        default: 'main'

permissions:
  contents: write

jobs:
  build-native:
    uses: ./.github/workflows/ci.yml
    secrets: inherit

  publish:
    needs: [build-native]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.commit_hash }}

      - name: Download All Artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Display Downloaded Files
        run: |
          ls -R artifacts

      - name: Generate Release Version & Info
        id: version_meta
        run: |
          # Use only the short commit hash for a clean version tag
          SHORT_SHA=$(git rev-parse --short HEAD)
          PKG_VERSION="v${SHORT_SHA}"
          
          echo "PKG_VERSION=$PKG_VERSION" >> $GITHUB_OUTPUT
          
          SHA=$(git rev-parse HEAD)
          cat << EOF > RELEASE_INFO.md
          Native Dawn release ${PKG_VERSION}
          Built from upstream revision: <https://dawn.googlesource.com/dawn/+log/${SHA}>.

          This repository delivers automated native desktop prebuilt binaries. 
          Provided as a best-effort service, not signed or officially guaranteed.
          EOF

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.version_meta.outputs.PKG_VERSION }}
          name: ${{ steps.version_meta.outputs.PKG_VERSION }}
          body_path: RELEASE_INFO.md
          files: |
            artifacts/**/Dawn-*.tar.gz
            artifacts/**/dawn-android-*.tar.gz
            artifacts/**/dawn-apple-*.xcframework.tar.gz
            artifacts/**/dawn-headers-*.tar.gz
